"""
Ship 14'.b (2026-07-22) — build the canonical Risk Register xlsx
template.

Unlike leaf-scoped templates (which live in `db/templates/*.md`
with TABLE-COLUMNS markers rendered per-tenant by
`rag/templates/xlsx_renderer.py`), the risk register is a
CROSS-LEAF surface: it spans req:6.1.2:risk_register (assessment)
and req:6.1.3:risk_treatment_plan (treatment). No single leaf
owns all 20+ columns.

This script builds a static reference xlsx that:
- Follows the workbook-importer's expected sheet + column names
  ("Risk Register" + "Risk Treatment Plan" per RowMappers.risks
  and RowMappers.risk_treatment in db/workbook_importer.py)
- Includes the 5 new ISO 27005:2022 §8.6.1 columns from
  schema_v87 (rationale, resources, KPIs, constraints, cadence)
- Ships a "Guidance" sheet with per-column 27005 authoritative
  language
- Includes a hidden `_arion_meta` sheet identifying the file as
  a canonical ArionComply risk register (auto-approve marker)

Output: `db/templates/risk_register_canonical.xlsx` (checked
into git as a static asset — regenerated by running this
script; deterministic, no runtime dependencies).

Framework role model discipline: the "ISMS Applicable Controls"
+ "PIMS Applicable Controls" columns get merged into the single
`control_refs TEXT[]` array by the importer, spanning program
+ extension roles as first-class citizens (no primary/xfw split).

Usage:
    PYTHONPATH=/data/arioncomply python3 \
        scripts/build_risk_register_template.py [--out PATH]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


_DEFAULT_OUT = Path("/data/arioncomply/db/templates/risk_register_canonical.xlsx")


# Register sheet columns (matches RowMappers.risks in workbook_importer.py)
_REGISTER_COLS: list[tuple[str, str]] = [
    ("Risk ID",           "Unique risk identifier per row (e.g. R-001). "
                          "Rows without a Risk ID starting with 'R' are skipped."),
    ("Asset ID",          "Cross-reference to your asset inventory. Optional."),
    ("Asset Name",        "Human-readable asset name."),
    ("Interested Party",  "Which stakeholder the risk affects "
                          "(customer / regulator / employee / etc.)"),
    ("Threat",            "The threat source / event (per ISO 27005:2022 §7.2 — "
                          "risk identification includes threat sources)."),
    ("Vulnerability",     "The vulnerability the threat exploits."),
    ("Likelihood",        "Integer 1-5. 1 = rare, 5 = almost certain."),
    ("Impact",            "Integer 1-5. 1 = negligible, 5 = catastrophic."),
    ("Risk Score",        "Likelihood × Impact (1-25). Populate manually or "
                          "leave blank — importer expects the row."),
    ("Risk Owner",        "Person or role accountable for treating this risk "
                          "(per ISO 27005:2022 §7.2.2 — risk owners have "
                          "accountability and authority)."),
]


# Treatment Plan sheet columns (matches RowMappers.risk_treatment,
# extended with 5 new columns from schema_v87)
_TREATMENT_COLS: list[tuple[str, str]] = [
    ("Risk ID",                                "Cross-reference to Risk Register sheet. Upserts on this key."),
    ("Treatment Option",                       "One of: Mitigate / Accept / Transfer / Avoid "
                                               "(per ISO 27005:2022 §8.2 — the four treatment options)."),
    ("Treatment Rationale",                    "Why this option was selected + expected benefits "
                                               "(per 27005:2022 §8.6.1 — first required plan element)."),
    ("Treatment Action",                       "The specific action(s) that implement the treatment."),
    ("ISMS Applicable Controls",               "Space-delimited ISO 27001:2022 controls, one per line "
                                               "or comma-separated. e.g. `A.5.15 A.8.24`."),
    ("PIMS Applicable Controls",               "Space-delimited ISO 27701:2019 controls. "
                                               "e.g. `A.7.5.1 B.8.5.4`. First-class alongside ISMS."),
    ("Resources Required",                     "Budget / people / infrastructure "
                                               "(per 27005:2022 §8.6.1)."),
    ("Performance Indicators",                 "KPIs demonstrating treatment effectiveness. "
                                               "Multi-line or comma-separated "
                                               "(per 27005:2022 §8.6.1)."),
    ("Constraints",                            "Dependencies, timing gates, prerequisites "
                                               "(per 27005:2022 §8.6.1)."),
    ("Reporting Cadence",                      "How often status is reported to the risk owner "
                                               "(per 27005:2022 §8.6.1)."),
    ("Implementation Date",                    "YYYY-MM-DD. Planned or actual — when the treatment "
                                               "becomes operational."),
    ("Residual Risk Level after Treatment",    "Integer 1-25 — where the risk sits after the "
                                               "treatment lands. Per 27005:2022 §8.6.3, this drives "
                                               "the residual-risk acceptance decision."),
    ("Status",                                 "One of: open / in_progress / implemented / accepted. "
                                               "Text 'in-progress' or 'In Progress' also accepted."),
    ("Review Date",                            "YYYY-MM-DD. When the treatment effectiveness will be "
                                               "reviewed next."),
    ("Effectivness Review",                    "Findings from the latest effectiveness review "
                                               "(intentional typo — matches existing importer key)."),
]


def _style_header(ws, col_count: int) -> None:
    header_fill = PatternFill("solid", fgColor="3A382E")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    thin = Side(border_style="thin", color="C8C5B8")
    border = Border(top=thin, bottom=thin, left=thin, right=thin)
    for col_ix in range(1, col_count + 1):
        cell = ws.cell(row=1, column=col_ix)
        cell.fill = header_fill
        cell.font = header_font
        cell.border = border
        cell.alignment = Alignment(wrap_text=True, vertical="center")


def _add_blank_rows(ws, col_count: int, n_rows: int = 10) -> None:
    thin = Side(border_style="thin", color="E8E5DA")
    border = Border(top=thin, bottom=thin, left=thin, right=thin)
    for _ in range(n_rows):
        ws.append([""] * col_count)
        for col_ix in range(1, col_count + 1):
            cell = ws.cell(row=ws.max_row, column=col_ix)
            cell.border = border
            cell.alignment = Alignment(wrap_text=True, vertical="top")


def _set_widths(ws, cols: list[tuple[str, str]]) -> None:
    for col_ix, (header, _) in enumerate(cols, start=1):
        width = max(16, min(40, int(len(header) * 1.2 + 6)))
        ws.column_dimensions[get_column_letter(col_ix)].width = width


def build_workbook() -> Workbook:
    wb = Workbook()

    # Sheet 1: Risk Register (assessment)
    ws1 = wb.active
    ws1.title = "Risk Register"
    ws1.append([c[0] for c in _REGISTER_COLS])
    _style_header(ws1, len(_REGISTER_COLS))
    _add_blank_rows(ws1, len(_REGISTER_COLS))
    _set_widths(ws1, _REGISTER_COLS)
    ws1.freeze_panes = "A2"

    # Sheet 2: Risk Treatment Plan
    ws2 = wb.create_sheet("Risk Treatment Plan")
    ws2.append([c[0] for c in _TREATMENT_COLS])
    _style_header(ws2, len(_TREATMENT_COLS))
    _add_blank_rows(ws2, len(_TREATMENT_COLS))
    _set_widths(ws2, _TREATMENT_COLS)
    ws2.freeze_panes = "A2"

    # Sheet 3: Guidance
    ws3 = wb.create_sheet("Guidance")
    ws3.append(["Sheet", "Column", "27005 § reference + what to fill in"])
    _style_header(ws3, 3)
    for hdr, guide in _REGISTER_COLS:
        ws3.append(["Risk Register", hdr, guide])
    for hdr, guide in _TREATMENT_COLS:
        ws3.append(["Risk Treatment Plan", hdr, guide])
    # Style body
    thin = Side(border_style="thin", color="E8E5DA")
    border = Border(top=thin, bottom=thin, left=thin, right=thin)
    for row_ix in range(2, ws3.max_row + 1):
        for col_ix in (1, 2, 3):
            cell = ws3.cell(row=row_ix, column=col_ix)
            cell.border = border
            cell.alignment = Alignment(wrap_text=True, vertical="top")
    ws3.column_dimensions["A"].width = 22
    ws3.column_dimensions["B"].width = 40
    ws3.column_dimensions["C"].width = 90
    ws3.freeze_panes = "A2"

    # Sheet 4: HIDDEN _arion_meta (auto-approve marker + provenance)
    ws4 = wb.create_sheet("_arion_meta")
    ws4.sheet_state = "hidden"
    ws4.append(["key", "value"])
    ws4.append(["template_kind",     "risk_register_canonical"])
    ws4.append(["template_version",  "1"])
    ws4.append(["schema_version",    "v87"])
    ws4.append(["guidance_source",   "ISO 27005:2022 §8.6.1"])
    ws4.append(["ship_arc",          "14'.b"])
    ws4.append(["auto_approve",      "true"])
    ws4.append(["register_leaf_id",  "req:6.1.2:risk_register"])
    ws4.append(["treatment_leaf_id", "req:6.1.3:risk_treatment_plan"])

    return wb


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=_DEFAULT_OUT)
    args = ap.parse_args()

    wb = build_workbook()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    wb.save(args.out)
    print(f"Wrote {args.out} ({args.out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
