"""
scripts/stage1_queue_sweep.py — bulk-approve / soft-delete pending findings.

Used to clear a tenant's Stage-1 queue after a curation refactor or
during dev when the queue has accumulated. Performs three operations
in order:

  1. Soft-delete pending findings whose checklist_item_id is NOT in
     the current catalog. These can't reach the engine — they bind to
     MUSTs Neo4j doesn't know about, so approving them is a no-op.
  2. Bulk approve everything else (catalog-resolved + Phase-1 coarse
     findings with NULL checklist_item_id).
  3. After this script, the caller should re-run xfw_proposer
     (propose_backfill) so cross-framework bridges regenerate against
     the current catalog refs.

CATALOG MEMBERSHIP — read this before modifying.

    The catalog union MUST match what `enrichment/documents/load_to_neo4j.py`
    treats as valid (line ~471): `ALL_EVIDENCE_REQUIREMENTS` UNION
    `DerivedSpec.direct_evidence`. A naive `dir(drm) + isinstance(EvidenceRequirement)`
    scan misses leaves nested inside DerivedSpec — and on 2026-06-27 a
    sweep using that wrong predicate soft-deleted 96 valid GDPR findings
    that were "missing from catalog" only because they were nested in
    DerivedSpec.direct_evidence (e.g. req:Art.16:rectification_procedure
    inside spec:GDPR:Art.16). 44 of those were restored; 52 had been
    cleared+regenerated by the xfw backfill (no data lost). See
    [[feedback-validate-set-membership]] + [[stage1-queue-sweep-2026-06-27]].

    The fixed predicate below uses the canonical union.

Run as superuser (bypasses RLS — required to write across all rows
for the tenant). Local pg_hba is configured to trust arioncomply
from 127.0.0.1, so no password is needed.

  $ PYTHONPATH=/data/arioncomply python3 scripts/stage1_queue_sweep.py            # dry-run
  $ PYTHONPATH=/data/arioncomply python3 scripts/stage1_queue_sweep.py --apply    # execute
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import psycopg2

from enrichment.documents.document_requirements import (
    ALL_EVIDENCE_REQUIREMENTS,
    ALL_DERIVED_SPECS,
)


# Arion tenant — only client today. Generalize when needed.
TENANT_ID = "00000000-0000-0000-0000-000000000001"

# Audit attribution — the consultant user uuid on Arion (FK to users).
# Could be parameterised but a single dev tenant doesn't need it.
SWEEP_USER_UUID = "86bc9bab-ae84-44e2-bab1-f52ffdf03917"


def _build_canonical_catalog() -> set[str]:
    """Compute the SAME catalog-item set the loader uses for valid_ev_ids.

    Matches `enrichment/documents/load_to_neo4j.py:471`:

        valid_ev_ids = {r.id for r in ALL_EVIDENCE_REQUIREMENTS} \
                     | {req.id for ds in ALL_DERIVED_SPECS
                                for req in ds.direct_evidence}

    For the item-level catalog, we walk must_contain + should_contain
    across both populations.
    """
    all_ers = list(ALL_EVIDENCE_REQUIREMENTS) + [
        er for ds in ALL_DERIVED_SPECS for er in ds.direct_evidence
    ]
    items: set[str] = set()
    for er in all_ers:
        for ci in list(er.must_contain) + list(er.should_contain):
            items.add(ci.id)
    return items


def connect_super():
    """Local pg_hba trusts arioncomply on 127.0.0.1 — no password needed.
    Bypasses RLS so we can sweep across the tenant uniformly."""
    return psycopg2.connect(
        host="127.0.0.1",
        user="arioncomply",
        database="arioncomply_compliance",
    )


def main(dry_run: bool):
    catalog = _build_canonical_catalog()
    print(f"Canonical catalog ChecklistItems: {len(catalog)}")
    # Sanity check: Neo4j should match this exactly. If they differ, the
    # loader hasn't been run after a catalog change — STOP and run it
    # first (`PYTHONPATH=/data/arioncomply python3
    # enrichment/documents/load_to_neo4j.py`) before sweeping.

    conn = connect_super()
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id, inference_source, checklist_item_id
              FROM document_findings
             WHERE tenant_id     = %s::uuid
               AND is_active     = TRUE
               AND review_status = 'pending'
            """,
            (TENANT_ID,),
        )
        rows = cur.fetchall()

    print(f"Pending findings: {len(rows)}")
    stale_ids: list[str] = []
    valid_ids: list[str] = []
    for fid, _src, item_id in rows:
        if item_id is None or item_id in catalog:
            valid_ids.append(fid)
        else:
            stale_ids.append(fid)
    print(f"  → stale (catalog-dead, soft-delete): {len(stale_ids)}")
    print(f"  → valid (bulk approve):              {len(valid_ids)}")
    if stale_ids and len(stale_ids) > 10:
        print(f"  ⚠ {len(stale_ids)} stale is high — verify the catalog "
              f"predicate matches the loader (see header).")

    if dry_run:
        print("\nDRY RUN — no DB writes. Re-run with --apply to execute.")
        return

    with conn.cursor() as cur:
        if stale_ids:
            cur.execute(
                """
                UPDATE document_findings
                   SET is_active = FALSE,
                       rejection_reason = 'catalog-dead refs: item_id no longer in catalog '
                                       || '(stage1_queue_sweep)',
                       reviewed_at = COALESCE(reviewed_at, NOW())
                 WHERE id = ANY(%s::uuid[])
                """,
                (stale_ids,),
            )
            print(f"  ✓ soft-deleted {cur.rowcount} stale findings")
        if valid_ids:
            cur.execute(
                """
                UPDATE document_findings
                   SET review_status = 'approved',
                       reviewed_at   = NOW(),
                       confirmed_by  = %s::uuid,
                       confirmed_at  = NOW()
                 WHERE id = ANY(%s::uuid[])
                """,
                (SWEEP_USER_UUID, valid_ids),
            )
            print(f"  ✓ approved {cur.rowcount} valid findings")
        conn.commit()
    print()
    print("Next: run xfw_proposer.propose_backfill for the tenant to")
    print("refresh cross-framework bridges against the current catalog:")
    print()
    print("  PYTHONPATH=/data/arioncomply python3 -c \\")
    print("    'from rag.intake.xfw_proposer import propose_backfill; ...'")
    print()
    print("Then load_posture(conn, tenant_id) to reconcile the engine.")


if __name__ == "__main__":
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--apply", action="store_true",
                   help="Execute writes (default: dry-run)")
    args = p.parse_args()
    main(dry_run=not args.apply)
